routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::namespace('App\Http\Controllers\Admin')->middleware(['auth'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('index');

    Route::resource('fornecedores', 'SupplierController')->names('suppliers')->parameters([
        'fornecedores' => 'fornecedor',
    ]);
    Route::get('fornecedores/{fornecedor}/deletar', 'SupplierController@delete')->name('suppliers.delete');
});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Supplier extends Model
{
    use HasFactory, SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'cnpj',
        'cnpj_legal_name',
        'cnpj_trade_name',
        'cnpj_ie_indicator',
        'cnpj_ie',
        'cnpj_im',
        'cnpj_status',
        'cnpj_tax_collection_type',
        'is_active',
        'cpf',
        'name',
        'nickname',
        'rg',
        'description',
        'type',
    ];

    const IE_INDICATOR = [
        0 => 'Contribuinte',
        1 => 'Contribuinte Isento',
        2 => 'Não Contribuinte',
    ];

    const TAX_COLLECTON_TYPE = [
        0 => 'A Recolher Pelo Prestador',
        1 => 'Retido Pelo Tomador',
    ];

    const IS_ACTIVE = [
        0 => 'Não',
        1 => 'Sim',
    ];

    const TYPES = [
        0 => 'Pessoa Jurídica',
        1 => 'Pessoa Física',
    ];

    public function getIsActiveStrAttribute()
    {
        return $this::IS_ACTIVE[$this->is_active];
    }

    public function contacts()
    {
        return $this->hasMany(Contact::class);
    }

    public function address()
    {
        return $this->hasOne(Address::class)->withDefault();
    }
}

app/Http/Controllers/Admin/SupplierController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\SupplierRequest;
use App\Models\Address;
use App\Models\Contact;
use App\Models\State;
use App\Models\Supplier;
use App\Service\Admin\SupplierService;

class SupplierController extends Controller
{
    public function index()
    {
        $suppliers = Supplier::select(['id', 'cnpj_legal_name', 'name', 'nickname', 'cnpj_trade_name', 'cnpj', 'cpf', 'is_active'])->get();

        return view('admin.suppliers.index', compact('suppliers'));
    }

    public function create($edit = false)
    {
        return view('admin.suppliers.create', compact('edit'));
    }

    public function store(SupplierRequest $request)
    {
        (new SupplierService())->createSupplier($request->validated());
        toast('Fornecedor criado com sucesso.', 'success');

        return redirect()->route('admin.suppliers.index');
    }

    /**
     * @param  Supplier  $supplier - Instância da model.
     * @param  bool  $edit - variável de controle utilizada no form.
     *
     * @var Address address - Instacia da relação de endereço do fornecedor
     * @var Contact contacts - Collection de contatos do fornecedor
     * @var Illuminate\Database\Eloquent\Builder - Contatos principais
     * @var Illuminate\Database\Eloquent\Builder - Contatos adicionais
     * @var Contact - Dados do primeiro contato adicional da lista
     * @var Illuminate\Support\Collection - Lista das cidades para popular o form
     */
    public function show(Supplier $supplier, $edit = true)
    {
        $address = $supplier->address;
        $contacts = $supplier->contacts;
        $mainContacts = $contacts->where('type', Contact::CONTACT_MAIN);
        $additionalContacts = $contacts->where('type', Contact::CONTACT_ADDITIONAL);
        $additionalContact = $additionalContacts->first();
        $cities = State::find($address->state_id)->cities()->orderBy('name')->pluck('name', 'id');

        return view('admin.suppliers.show', compact('supplier', 'edit', 'address', 'mainContacts', 'additionalContacts', 'additionalContact', 'cities'));
    }

    /**
     * @param  Supplier  $supplier - Instância da model.
     * @param  bool  $edit - variável de controle utilizada no form.
     *
     * @var Address address - Instacia da relação de endereço do fornecedor
     * @var Contact contacts - Collection de contatos do fornecedor
     * @var Illuminate\Database\Eloquent\Builder - Contatos principais
     * @var Illuminate\Database\Eloquent\Builder - Contatos adicionais
     * @var Contact - Dados do primeiro contato adicional da lista
     * @var Illuminate\Support\Collection - Lista das cidades para popular o form
     */
    public function edit(Supplier $supplier, $edit = true)
    {
        $address = $supplier->address;
        $contacts = $supplier->contacts;
        $mainContacts = $contacts->where('type', Contact::CONTACT_MAIN);
        $additionalContacts = $contacts->where('type', Contact::CONTACT_ADDITIONAL);
        $additionalContact = $additionalContacts->first();
        $cities = State::find($address->state_id)->cities()->orderBy('name')->pluck('name', 'id');

        return view('admin.suppliers.edit', compact('supplier', 'edit', 'address', 'mainContacts', 'additionalContacts', 'additionalContact', 'cities'));
    }

    public function update(SupplierRequest $request, Supplier $supplier)
    {
        (new SupplierService())->updateSupplier($supplier, $request->validated());
        toast('Fornecedor atualizado com sucesso.', 'success');

        return redirect()->route('admin.suppliers.index');
    }

    public function destroy(Supplier $supplier)
    {
        $supplier->delete();

        toast('Fornecedor removido com sucesso.', 'success');

        return redirect()->route('admin.suppliers.index');
    }

    /**
     * Exibe a view para deletar Fornecedor
     */
    public function delete(Supplier $supplier)
    {
        return view('admin.suppliers.delete', compact('supplier'));
    }
}

resources/views/admin/suppliers/create.blade.php
@extends('layouts.app')

@section('title', 'Fornecedor Criar')

@section('content_header')
    <div class="row mb-3">
        <div class="col-md-10">
            <h1>Fornecedor - <small>Criar</small> </h1>
        </div>
    </div>
@stop

@section('content')
{{ Form::open(['route'=> ['admin.suppliers.store'], 'method'=>'POST', 'id' => 'formCreate', 'class'=>'pb-4']) }}

    @include('admin.suppliers._form')

    <x-adminlte-button class="btn-flat" type="submit" label="Salvar" theme="success" icon="fas fa-lg fa-save"/>
{{ Form::close() }}
@stop

@push('js')
{!! JsValidator::formRequest('App\Http\Requests\Admin\SupplierRequest', '#formCreate'); !!}
<script>
    $(document).ready(function(){
        $('#formCreate').on('submit', ()=> $(".form-check-inline #type-error").hide());
    });
</script>

@endpush

resources/views/admin/suppliers/delete.blade.php
@extends('layouts.app')

@section('title', 'Fornecedor Excluir')

@section('content_header')
    <div class="row mb-3">
        <div class="col-md-10">
            <h1>Fornecedor - <small>Excluir</small> </h1>
        </div>
    </div>
@stop

@section('content')
<x-adminlte-card title="Registro" theme="light" icon="fas fa-lg fa-exclamation" collapsible>
    <div class="form-group">
        @if($supplier->cpf)
        <label class="control-label"> Nome/Apelido </label>
        <input type="text" class="form-control" value="{{$supplier->name}}/{{$supplier->nickname}}" readonly="">
        @else
        <label class="control-label"> Razão Social/Nome Fantasia </label>
        <input type="text" class="form-control" value="{{$supplier->cnpj_legal_name}}/{{$supplier->cnpj_trade_name}}" readonly="">
        @endif
    </div>
</x-adminlte-card>
{{ Form::open(['route'=> ['admin.suppliers.destroy', $supplier->id], 'method'=>'DELETE', 'id' => 'formDelete']) }}
<button type="submit" onClick="" class="btn btn-sm btn-danger">
    <i class="fas fa-sm fa-trash"></i> Excluir
</button>
{{ Form::close() }}

@stop

@section('js')
<script>
$('form#formDelete').submit((e)=>{
    e.preventDefault();
    const confirmed = confirm('Tem certeza que deseja excluir esse fornecedor?');
    if(confirmed) { e.target.submit(); }
})
</script>
@endsection

resources/views/admin/suppliers/edit.blade.php
@extends('layouts.app')

@section('title', 'Edição de Fornecedor')

@section('content_header')
    <div class="row mb-3">
        <div class="col-md-10">
            <h1>Fornecedor - <small>Editar</small> </h1>
        </div>
    </div>
@stop

@section('content')
{{ Form::model($supplier, ['route'=> ['admin.suppliers.update', $supplier->id], 'method'=>'PUT', 'id' => 'formUpdate', 'class'=>'pb-4']) }}

    @include('admin.suppliers._form')

    <x-adminlte-button class="btn-flat" type="submit" label="Salvar" theme="success" icon="fas fa-lg fa-save"/>
{{ Form::close() }}
@stop

@push('js')
{!! JsValidator::formRequest('App\Http\Requests\Admin\SupplierRequest', '#formUpdate'); !!}
<script>
    $(document).ready(function(){
        $('#formUpdate').on('submit', ()=> $(".form-check-inline #type-error").hide());
    });
</script>

@endpush

resources/views/admin/suppliers/index.blade.php
@extends('layouts.app')

@section('title', 'Fornecedores')

@section('content_header')
    <div class="row mb-3">
        <div class="col-md-10">
            <h1>Fornecedores - <small>Painel de Controle</small> </h1>
        </div>
        <div class="col-md-2">
            <a href="{{route('admin.suppliers.create')}}">
                <button class="btn btn-block btn-success" z="">
                    <i class="fa fa-plus fa-fw"></i> Cadastrar
                </button>
            </a>
        </div>
    </div>
@stop

@section('content')
<section class="p-4 bg-white">
    {{-- Table --}}
    <div class="table-responsive">
        <table style="width:100%" class="table table-bordered datatable">
            {{-- Table head --}}
            <thead>
                <tr>
                    <th>Razão Social/Nome</th>
                    <th>Nome Fantasia/Apelido</th>
                    <th>CNPJ/CPF</th>
                    <th>Ativo</th>
                    <th>Ação</th>
                </tr>
            </thead>
                @foreach ($suppliers as $supplier)
                <tr>
                    <td>{{ $supplier->cnpj_legal_name ?? $supplier->name }}</td>
                    <td>{{ $supplier->cnpj_trade_name ?? $supplier->nickname }}</td>
                    <td class="@if($supplier->cnpj) cnpj @else cpf @endif">{{ $supplier->cnpj ?? $supplier->cpf }}</td>
                    <td>{{ $supplier->is_active_str }}</td>
                    <td>
                        <a href="{{route('admin.suppliers.edit', [$supplier->id])}}" class="btn btn-xs btn-default text-primary mx-1 shadow" title="Editar">
                            <i class="fa fa-lg fa-fw fa-pen"></i>
                        </a>
                        <a href="{{route('admin.suppliers.show', [$supplier->id])}}" class="btn btn-xs btn-default text-teal mx-1 shadow" title="Ver">
                            <i class="fa fa-lg fa-fw fa-eye"></i>
                        </a>
                        <a href="{{route('admin.suppliers.delete', [$supplier->id])}}" class="btn btn-xs btn-default text-danger mx-1 shadow" title="Excluir">
                            <i class="fa fa-lg fa-fw fa-trash"></i>
                        </a>
                    </td>
                </tr>
                @endforeach
            <tbody>
            </tbody>
        </table>
    </div>
</section>
@stop

@push('css')
<style type="text/css">
    .datatable tr td,  .datatable tr th {
        vertical-align: middle;
    }
</style>
@endpush

@push('js')
<script>
    $(() => {
        $('.datatable').DataTable({
            lengthMenu: [10, 50, 100, 200],
            order: [
                [0, "asc"]
            ],
            language: {
                url: "{{asset('/vendor/datatables/js/pt-br.json')}}"
            },
        });
    })
</script>
<script>
$(document).ready(function(){
    $('.cpf').mask('000.000.000-00', {reverse: true});
  $('.cnpj').mask('00.000.000/0000-00', {reverse: true});
});
</script>
@endpush

resources/views/admin/suppliers/show.blade.php
@extends('layouts.app')

@section('title', 'Fornecedor Editar')

@section('content_header')
    <div class="row mb-3">
        <div class="col-md-10">
            <h1>Fornecedor - <small>Ver</small> </h1>
        </div>
    </div>
@stop

@section('content')
{{ Form::model($supplier, ['route'=> ['admin.suppliers.store'], 'method'=>'PUT', 'id' => 'formCreate', 'class'=>'pb-4']) }}

<fieldset disabled>
    @include('admin.suppliers._form')
</fieldset>

<a href="{{route('admin.suppliers.edit', [$supplier->id])}}" class="btn btn-sm btn-primary">
    <i class="fa fa-edit fa-fw"></i> Editar
</a>
{{ Form::close() }}
@stop

@push('js')
{!! JsValidator::formRequest('App\Http\Requests\Admin\Supplier\StoreRequest', '#formCreate'); !!}
<script>
    $(document).ready(function(){
        $('.summernote').summernote('disable');
    });
</script>

@endpush